server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #\u7533\u660E\u81EA\u5DF1\u662F\u4E2A\u670D\u52A1\u7AEF
    register-with-eureka: false
    fetch-registry: false
    #\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #\u5173\u95ED\u81EA\u6211\u4FDD\u62A4,\u4E0D\u5EFA\u8BAE\u5173\u95ED,false\u4E3A\u5173\u95ED
  server:
    enable-self-preservation: false